enabled: false
export_interval: 5
log_types:
- windows_security
- windows_system
file_paths:
  windows_security: logs/system/windows_security.log
  windows_system: logs/system/windows_system.log
max_batch_size: 100
batch_interval: 5.0
enforce_killswitch: true
